// src/pages/dashboard/DashboardSampleData.ts
// Datos de ejemplo para el calendario. Se sustituirán por datos de Supabase en tiempo real.
import { Task } from '../../types/dashboard';

export const SAMPLE_TASKS: Task[] = [
  {
    id: '1',
    title: 'Revisión KPIs Centros',
    startDate: '2025-01-20',
    startTime: '10:30',
    endTime: '11:00',
    isRecurring: true,
    recurrenceRule: { pattern: 'weekly', interval: 1, daysOfWeek: [1] },
    category: 'meeting',
    meetingType: 'weekly',
    priority: 'high',
    status: 'pending',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '2',
    title: 'Reunión RRHH Semanal',
    startDate: '2025-01-21',
    startTime: '09:00',
    endTime: '10:00',
    isRecurring: true,
    recurrenceRule: { pattern: 'weekly', interval: 1, daysOfWeek: [2] },
    category: 'meeting',
    meetingType: 'weekly',
    department: 'RRHH y Procedimientos',
    assignmentType: 'corporativo',
    assignmentId: 'RRHH y Procedimientos',
    priority: 'high',
    status: 'pending',
    description: 'Revisión semanal de ausencias, incidencias y procedimientos del departamento',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '3',
    title: 'Auditoría Sevilla',
    startDate: '2025-01-22',
    startTime: '11:00',
    endTime: '13:00',
    isRecurring: false,
    category: 'audit',
    priority: 'medium',
    status: 'pending',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '4',
    title: 'Reunión Marketing Mensual',
    startDate: '2025-01-23',
    startTime: '16:00',
    endTime: '17:00',
    isRecurring: true,
    recurrenceRule: { pattern: 'monthly', interval: 1 },
    category: 'meeting',
    meetingType: 'monthly',
    department: 'Marketing',
    priority: 'high',
    status: 'pending',
    description: 'Revisión de contenido publicado, estrategia de redes sociales y campañas',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '5',
    title: 'Planificación Mensual',
    startDate: '2025-01-24',
    startTime: '10:00',
    endTime: '12:00',
    isRecurring: false,
    category: 'task',
    priority: 'high',
    status: 'pending',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '6',
    title: 'Formación Empleados',
    startDate: '2025-01-27',
    startTime: '09:30',
    endTime: '11:30',
    isRecurring: false,
    category: 'task',
    priority: 'medium',
    status: 'pending',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '7',
    title: 'Reunión Logística',
    startDate: '2025-01-28',
    startTime: '15:00',
    endTime: '16:00',
    isRecurring: true,
    recurrenceRule: { pattern: 'weekly', interval: 1, daysOfWeek: [2] },
    category: 'meeting',
    meetingType: 'weekly',
    department: 'Logística',
    assignmentType: 'corporativo',
    assignmentId: 'Logística',
    priority: 'medium',
    status: 'pending',
    description: 'Revisión de stock, pedidos y gestión de inventario',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '8',
    title: 'Evaluación Trimestral',
    startDate: '2025-01-31',
    startTime: '14:00',
    endTime: '16:00',
    isRecurring: false,
    category: 'review',
    priority: 'high',
    status: 'pending',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
  {
    id: '9',
    title: 'Reunión Encargado Sevilla',
    startDate: '2025-01-29',
    startTime: '11:00',
    endTime: '12:00',
    isRecurring: true,
    recurrenceRule: { pattern: 'weekly', interval: 1, daysOfWeek: [3] },
    category: 'meeting',
    meetingType: 'weekly',
    assignmentType: 'centro',
    assignmentId: 'francisco-giraldez',
    priority: 'high',
    status: 'pending',
    description: 'Reunión semanal con el encargado del centro de Sevilla para revisar KPIs y operaciones',
    createdAt: '2025-01-15T10:00:00Z',
    updatedAt: '2025-01-15T10:00:00Z',
    createdBy: 'ceo',
  },
];
